<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [11]:
import numpy as np

In [21]:
A = np.array((1, 1, 1))
print (A)
B = np.array((3, 3, 3))
print (B)
n = np.subtract(B, A)
k = np.divide(B, 2)
l = np.transpose(k)
m = np.multiply(n,l)
f = m[0]+m[1]+m[2]
print ("Результат вычисления: ",-f)

[1 1 1]
[3 3 3]
Результат вычисления:  -9.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [28]:
import numpy as np
M = np.zeros((8,8))
M[0] = [-4, -3, -2, -6, -5, -2, -3, -4]
M[1] = [-1, -1, -1, -1, -1, -1, -1, -1]
M[6] = [1, 1, 1, 1, 1, 1, 1, 1]
M[7] = [4, 3, 2, 6, 5, 2, 3, 4]
print("Результат: ",M)

Результат:  [[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [2]:
import numpy as np
Mass = np.arange (2, 21, 2)
NMass = Mass + 1
result = Mass * NMass
print(result)

[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [5]:
# 4. Ваш код здесь
import numpy as np
arr = np.random.uniform (0, 20, size = (4, 7))
arr_normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
arr_rounded = np.round (arr_normalized, decimals = 4)
print(arr_rounded)

[[0.9218 1.     0.5865 0.9168 0.7084 0.014  0.843 ]
 [0.2771 0.2212 0.6972 0.7876 0.1184 0.0396 0.2997]
 [0.114  0.1028 0.4686 0.5662 0.1946 0.9813 0.0613]
 [0.0562 0.9355 0.429  0.     0.4625 0.3331 0.9703]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

Алгоритм решения:
1) my_array [1:4,1:4] указывает на то, что берутся строки с индексами от 1 до 4 (не включая 4) и столбцы с индексами от 1 до 4 (не включая), что соответствует центральному фрагменту массива с размером 3х3

In [6]:
# 5. Ваш код здесь
import numpy as np
my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
#Извлекаем центральный фрагмент размером 3х3
center_fragment = my_array [1:4,1:4]
print(center_fragment)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

Алгоритм решения:
1) Задаём массив
2) Строка my_sin = np.sin(my_array) используется для применения функции синуса np.sin к каждому элементу массива my_array
3) Потом, с помощью функции np.sum, вычисляется сумма всех элементов массива my_sin и сохраняется в переменную sum_sin
4) В конце, с помощью функции np.round, округляем значение sum_sin и до трех цифр после запятой

In [7]:
# 6. Ваш код здесь
import numpy as np
my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
#Создаём массива, состоящего из синусов элементов my_array
my_sin = np.sin(my_array)
#Сумма элементов массива my_array
sum_sin = np.sum(my_sin)
#Округление ответа до трех цифр после занятой
rounded_sum = np.round(sum_sin, decimals = 3)
print(rounded_sum)

1.936


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

Алгоритм решения:
1) Создаём пустое матрицу размером 4х5, инициализируя каждый элемент значением 0
2) Внешний цикл for выполняется 5 раз (для строк матрицы), внутренний цикл for выполняется 4 раза (для столбцов матрицы), затем получаем случайные числа с помощью функции random.randint(0,100)
3) Используем цикл for для перебора строк матрицы, затем выводим с помощью функции print()
4) [::-1] в обратном порядке по убыванию 
5) axis(параметр метода) =None: провести сортировку по всему массиву в целом, а не по какой-то конкретной оси 

In [17]:
# 7. Ваш код здесь
import numpy as np
import random
#Создаем пустой матрицы размером 4х5
matrix = [[0 for _ in range(4)]for _ in range(5)]
#Заполнение матрицы случайными целыми числами 
for i in range(5):
    for j in range(4):
        matrix[i][j] = random.randint(0,100)
#Вывод матрицы на экран
print("Матрица: ")
for row in matrix:
    print(row)
#Отсортировка 
sorted_matrix = np.sort(matrix, axis=None)[::-1]
#Получение второго сверху значения в матрице
second_value = sorted_matrix[1]
#Определение индекса этого значения
second_index = np.where (matrix == second_value)
print("\nВторое сверху значение: ",second_value)
print("Индекс этого значения: ",second_index)

Матрица: 
[34, 90, 45, 4]
[16, 77, 48, 100]
[79, 90, 64, 81]
[24, 77, 35, 92]
[61, 53, 8, 25]

Второе сверху значение:  92
Индекс этого значения:  (array([3], dtype=int64), array([3], dtype=int64))


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

Алгоритм решения:
1) Создаём два рандомных массива 
2) Печатем, округляя до двух знаков после запятой 
3) Создаётся третий массив, состоящий из нулей
4) Вводится счётчик для строк, в цикле мы идём по строкам,аналогично со столбцами. Затем мы берём и записываем в наш нулевой массив значения полученные с помощью функции
5) В функцию передаются массивы и номера операторов 

In [18]:
# 8. Ваш код здесь
def CreateMatrix(array1, array2, operator):
    result = np.zeros((4,7))
    if operator == "1":
        result = max(array1,array2)
    elif operator == "2":
        result = min(array1,array2)
    elif operator == "3":
        result = np.add(array1,array2)/2
    return result
    


ar1 = np.random.uniform(low=0, high=10, size=(4, 7))
ar2 = np.random.uniform(low=0, high=10, size=(4, 7))

print("ar1:\n",np.round(ar1,decimals = 2))
print("\nar2:\n",np.round(ar2,decimals = 2))

ar3 = np.zeros((4,7))

oper = input("\nВведите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): ")


i = 0
while i < 4:
    j = 0
    while j < 7:
        ar3[i][j] = CreateMatrix(ar1[i][j],ar2[i][j],oper)
        j += 1
    i +=1

print("\nar3:", np.round(ar3,decimals = 2))


ar1:
 [[0.99 2.09 4.23 6.23 3.26 6.92 2.97]
 [5.78 7.68 8.84 3.31 5.28 4.37 7.78]
 [9.07 8.11 6.44 6.46 9.7  3.37 8.46]
 [7.92 9.37 6.41 8.58 2.28 8.68 8.51]]

ar2:
 [[2.66 3.86 0.33 3.41 6.38 7.86 6.51]
 [8.35 3.08 5.55 4.8  2.76 2.87 9.39]
 [5.11 5.75 2.66 2.62 6.43 2.26 3.86]
 [3.97 7.54 7.24 8.02 8.72 8.11 2.51]]

Введите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): 2

ar3: [[0.99 2.09 0.33 3.41 3.26 6.92 2.97]
 [5.78 3.08 5.55 3.31 2.76 2.87 7.78]
 [5.11 5.75 2.66 2.62 6.43 2.26 3.86]
 [3.97 7.54 6.41 8.02 2.28 8.11 2.51]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

Алгоритм решения: 
1) great_array[great_array>50]: создает булев массив той же формы, что и great_array, где элементы, удовлетворяющие условию больше 50, будут равны True, а остальные элементы будут равны False.
great_array[great_array > 50] использует этот булев массив в качестве маски для выбора элементов из great_array, которые удовлетворяют условию больше 50. Таким образом, мы получим одномерный массив только из элементов, которые больше 50.

In [6]:
#9 Ваш код здесь
import numpy as np
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
#Создаём массив great_array
great_array = np.array([first,second,third])
#Вычисление суммы элементов массива, значение которых больше 50
filtered_array = great_array[great_array>50]
sum_of_values = np.sum(filtered_array)
print("Сумма элементов массива, значение которых больше 50: ", sum_of_values)

Сумма элементов массива, значение которых больше 50:  5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

Алгоритм решения:
1) Метод flatten() для массива great_array приведет к тому, что многомерный массив будет преобразован в одномерный массив. Это означает, что все элементы из всех подмассивов будут расположены последовательно в одной строке

In [7]:
# 10. Ваш код здесь

#Переводим в одномерную форму
one_dim_array = great_array.flatten()
value_at_index_150 = one_dim_array[150]
print("Ответ: ",value_at_index_150)


Ответ:  5.313292845913055


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

Алгоритм решения:
1) np.where-это функиця, которая возвращает индексы элементов, удовлетворяющих условию

In [8]:
# 11.
import numpy as np
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь
indices = np.where (A == B) [0]
print("array",indices)

array [1 3 5 7]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

Алгоритм решения: 
1) array2: каждому значению первого массива прибовляем один, таким образом получаем массив нечетных чисел
2) array3: это массив,в котором каждый элемент получен путем умножения соответствующих элементов массивов array1 и array2
3) np.column_stack-этот метод используется для объединения массивов array1, array2 и array3 в один двумерный массив,в котором исходные массивы расположены в столбцах

In [11]:
# 12.  Ваш код здесь
import numpy as np
array1 = np.array ([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
array2 = array1 + 1
array3 = np.multiply(array1,array2)
#Соединяем все массивы в один двумерный массив
result_array = np.column_stack((array1,array2,array3))
print(result_array)

[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
